#!/usr/bin/env bash
#Write a Bash script that pings an IP address passed as an argument
port=$1
	if [[ -z $port ]];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$port" -c5
fi
