#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
sudo cp /etc/hosts ~/hosts.modified
echo "127.0.0.2		localhost" > ~/hosts.modified
echo "8.8.8.8		facebook.com">> ~/hosts.modified
sudo cp -f ~/hosts.modified /etc/hosts
